services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    restart: unless-stopped
    environment:
      - INSECURE=true
      - DISABLE_IPV6=true
    volumes:
      - ./wg-easy:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp" # WebUI
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      wireguard-adguard:
        ipv4_address: 10.0.0.10

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    expose:
      - "3000" # WebUI, accessibile solo dalla rete Docker
    networks:
      wireguard-adguard:
        ipv4_address: 10.0.0.11

networks:
  wireguard-adguard:
    name: wireguard-adguard
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
